CREATE TABLE IF NOT EXISTS `ai_pipeline_provider_resource` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `created_at` DATETIME NULL COMMENT '创建时间',
  `updated_at` DATETIME NULL COMMENT '更新时间',
  `is_deleted` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '逻辑删除标记',
  `resource_id` VARCHAR(128) NOT NULL COMMENT '资源稳定标识',
  `provider_name` VARCHAR(128) NOT NULL COMMENT '运行时 provider 名称',
  `display_name` VARCHAR(255) NOT NULL COMMENT '展示名称',
  `description` TEXT NULL COMMENT '资源描述',
  `kind` VARCHAR(64) NOT NULL COMMENT 'provider 类型',
  `role` VARCHAR(64) NOT NULL COMMENT 'provider 角色',
  `base_url` VARCHAR(512) NULL COMMENT 'provider base url',
  `api_key` TEXT NULL COMMENT 'provider api key',
  `model` VARCHAR(255) NULL COMMENT 'provider model',
  `timeout_seconds` FLOAT NOT NULL DEFAULT 60 COMMENT '超时时间',
  `temperature` FLOAT NOT NULL DEFAULT 0 COMMENT '默认温度',
  `max_tokens` INT NOT NULL DEFAULT 1024 COMMENT '默认最大 token',
  `extra_headers_json` TEXT NULL COMMENT '额外请求头 JSON',
  `extra_json` TEXT NULL COMMENT '额外配置 JSON',
  `enabled` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  `created_by` VARCHAR(64) NULL COMMENT '创建人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_pipeline_provider_resource_resource_id` (`resource_id`),
  UNIQUE KEY `uk_ai_pipeline_provider_resource_provider_name` (`provider_name`),
  KEY `idx_ai_pipeline_provider_resource_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='AI Pipeline Provider 资源表';
