spring:
  mvc:
    async:
      request-timeout: 600000
  application:
    name: automl
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: admin
      password: admin
      config:
        import-check:
          enabled: false
        namespace: public
        group: AUTO_ML
        file-extension: yaml
        ext-config:
          - data-id: DB
            group: AUTO_ML
            refresh: true
          - data-id: LOCAL_S3_CONFIG
            group: AUTO_ML
            refresh: true
  config:
    import:
      - nacos:DB?group=AUTO_ML
      - nacos:LOCAL_S3_CONFIG?group=AUTO_ML


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: isDeleted
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# http://localhost:8080/automl/swagger-ui/index.html#/
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

server:
  servlet:
    context-path: /automl

ai-platform:
  url: ${AI_PLATFORM:http://127.0.0.1:8000}
  get-label: /label/image
  video-process: /process/video
  describe-image: /process/describe